Trying to get TC to build with "require"
Was building fine no my machine, but fails on TC:

[tsl] ERROR in :\BuildAgent\work\a60551f5745e8904\src\BloomBrowserUI\bookEdit\js\origami.ts(13,1)
      TS2580: Cannot find name 'require

We don't want to add node types, because the client doesn't have node runtime. But https://stackoverflow.com/a/49299180/723299 suggests this might help.